### PR TITLE
Vuepress sample area

### PR DESCRIPTION
**Pull request by LeeLenaleee**
Added all area samples to the vuepress sampels, the multi chart samples I added as tabbed samples

### CODE REVIEW

**Comment by etimberg** [comment]
Thanks @LeeLenaleee

**Review by etimberg — APPROVED** [review]

**Comment by LeeLenaleee** [comment]
Did you and kurkle devide the work cuz I am happy willingly to do some more but would be a waste if double work is getting done

**Comment by etimberg** [comment]
We haven't divided it and I haven't done anything today. @kurkle did you have anything in work?

**Comment by kurkle** [comment]
nothing on currently. I'll continue with the advanced category

**Comment by LeeLenaleee** [comment]
Alright, I will start working on the linear scale section then

**Comment by LeeLenaleee** [comment]
Will start working on the other charts category tommorow, linear scale is done

**Comment by etimberg** [comment]
I got the "scriptable" section converted this evening.

**Pull request merged**
